version: '3'

services:

  backend:
    image: madmax27/backendspe:latest
    container_name: backend

    ports:
      - '8080:8080'

    restart: always

  frontend:
    image: madmax27/frontendspe:latest
    container_name: frontend

    ports:
      - "3000:3000"

    restart: always

    depends_on:
      - backend